/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package states.and.state.capitals;

import org.junit.jupiter.api.Test;
import states.and.state.capitals.statesAndCapitals.StatesAndCapitals;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
